In [1]:
print("hello")

hello

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\ayush\Downloads\datasets-for-ml-main\datasets-for-ml-main\covid_toy.csv")

print(df.head())

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
print(df.head(6))

   age  gender  fever cough       city has_covid
0   60    Male  103.0  Mild    Kolkata        No
1   27    Male  100.0  Mild      Delhi       Yes
2   42    Male  101.0  Mild      Delhi        No
3   31  Female   98.0  Mild    Kolkata        No
4   65  Female  101.0  Mild     Mumbai        No
5   84  Female    NaN  Mild  Bangalore       Yes

In [5]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [9]:
df['gender'] = df['gender'].map({'female': 1, 'male': 0})

print(df['gender'])

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
95   NaN
96   NaN
97   NaN
98   NaN
99   NaN
Name: gender, Length: 100, dtype: float64

In [10]:
df.filter(items =['gender','city'])

    gender       city
0      NaN    Kolkata
1      NaN      Delhi
2      NaN      Delhi
3      NaN    Kolkata
4      NaN     Mumbai
..     ...        ...
95     NaN  Bangalore
96     NaN    Kolkata
97     NaN  Bangalore
98     NaN     Mumbai
99     NaN    Kolkata

[100 rows x 2 columns]

In [11]:
df[['fever','has_covid']]

    fever has_covid
0   103.0        No
1   100.0       Yes
2   101.0        No
3    98.0        No
4   101.0        No
..    ...       ...
95  104.0        No
96  101.0       Yes
97  101.0        No
98   98.0        No
99   98.0       Yes

[100 rows x 2 columns]

In [12]:
df.head(3)

   age  gender  fever cough     city has_covid
0   60     NaN  103.0  Mild  Kolkata        No
1   27     NaN  100.0  Mild    Delhi       Yes
2   42     NaN  101.0  Mild    Delhi        No

In [13]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [15]:
df['has_covid'] = df['has_covid'].map({"No": 0, "Yes": 1})
print(df['has_covid'])

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
95   NaN
96   NaN
97   NaN
98   NaN
99   NaN
Name: has_covid, Length: 100, dtype: float64

In [20]:
df['fever'] = df['fever'].fillna(0).astype(int)
print(df['fever'])

0     103
1     100
2     101
3      98
4     101
     ...
95    104
96    101
97    101
98     98
99     98
Name: fever, Length: 100, dtype: int64

In [22]:
df['age']=df['age'].astype(float)
print(df['age'])

0     60.0
1     27.0
2     42.0
3     31.0
4     65.0
      ...
95    12.0
96    51.0
97    20.0
98     5.0
99    10.0
Name: age, Length: 100, dtype: float64

In [23]:
df['fever'][1:3]=50

C:\Users\ayush\AppData\Local\Temp\ipykernel_8056\736839710.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['fever'][1:3]=50
C:\Users\ayush\AppData\Local\Temp\ipykernel_8056\736839710.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fever'][1:3]=50

In [24]:
df.head(3)

    age  gender  fever cough     city  has_covid
0  60.0     NaN    103  Mild  Kolkata        NaN
1  27.0     NaN     50  Mild    Delhi        NaN
2  42.0     NaN     50  Mild    Delhi        NaN

In [25]:
df['has_covid'] = df['has_covid'].map({"No": 0, "Yes": 1})
print(df['has_covid'])

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
95   NaN
96   NaN
97   NaN
98   NaN
99   NaN
Name: has_covid, Length: 100, dtype: float64

In [26]:
print(df.head(9))

    age  gender  fever   cough       city  has_covid
0  60.0     NaN    103    Mild    Kolkata        NaN
1  27.0     NaN     50    Mild      Delhi        NaN
2  42.0     NaN     50    Mild      Delhi        NaN
3  31.0     NaN     98    Mild    Kolkata        NaN
4  65.0     NaN    101    Mild     Mumbai        NaN
5  84.0     NaN      0    Mild  Bangalore        NaN
6  14.0     NaN    101  Strong  Bangalore        NaN
7  20.0     NaN      0  Strong     Mumbai        NaN
8  19.0     NaN    100  Strong  Bangalore        NaN

In [27]:
print(df['has_covid'].unique())

[nan]

In [28]:
df['has_covid'] = df['has_covid'].astype(str).str.strip().str.title()
df['has_covid'] = df['has_covid'].map({"No": 0, "Yes": 1})

print(df['has_covid'])

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
95   NaN
96   NaN
97   NaN
98   NaN
99   NaN
Name: has_covid, Length: 100, dtype: float64

In [29]:
df['city'][0]='jaipur'

C:\Users\ayush\AppData\Local\Temp\ipykernel_8056\935263761.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][0]='jaipur'
C:\Users\ayush\AppData\Local\Temp\ipykernel_8056\935263761.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][0]='jaipur'

In [30]:
df.head(3)

    age  gender  fever cough    city  has_covid
0  60.0     NaN    103  Mild  jaipur        NaN
1  27.0     NaN     50  Mild   Delhi        NaN
2  42.0     NaN     50  Mild   Delhi        NaN

In [31]:
df.rename(columns={"cough":"updated_cough"})

     age  gender  fever updated_cough       city  has_covid
0   60.0     NaN    103          Mild     jaipur        NaN
1   27.0     NaN     50          Mild      Delhi        NaN
2   42.0     NaN     50          Mild      Delhi        NaN
3   31.0     NaN     98          Mild    Kolkata        NaN
4   65.0     NaN    101          Mild     Mumbai        NaN
..   ...     ...    ...           ...        ...        ...
95  12.0     NaN    104          Mild  Bangalore        NaN
96  51.0     NaN    101        Strong    Kolkata        NaN
97  20.0     NaN    101          Mild  Bangalore        NaN
98   5.0     NaN     98        Strong     Mumbai        NaN
99  10.0     NaN     98        Strong    Kolkata        NaN

[100 rows x 6 columns]

In [32]:
df.rename(columns={"fever":"has_fever"})

     age  gender  has_fever   cough       city  has_covid
0   60.0     NaN        103    Mild     jaipur        NaN
1   27.0     NaN         50    Mild      Delhi        NaN
2   42.0     NaN         50    Mild      Delhi        NaN
3   31.0     NaN         98    Mild    Kolkata        NaN
4   65.0     NaN        101    Mild     Mumbai        NaN
..   ...     ...        ...     ...        ...        ...
95  12.0     NaN        104    Mild  Bangalore        NaN
96  51.0     NaN        101  Strong    Kolkata        NaN
97  20.0     NaN        101    Mild  Bangalore        NaN
98   5.0     NaN         98  Strong     Mumbai        NaN
99  10.0     NaN         98  Strong    Kolkata        NaN

[100 rows x 6 columns]

In [33]:
df.rename(columns={"age":"new_age"})

    new_age  gender  fever   cough       city  has_covid
0      60.0     NaN    103    Mild     jaipur        NaN
1      27.0     NaN     50    Mild      Delhi        NaN
2      42.0     NaN     50    Mild      Delhi        NaN
3      31.0     NaN     98    Mild    Kolkata        NaN
4      65.0     NaN    101    Mild     Mumbai        NaN
..      ...     ...    ...     ...        ...        ...
95     12.0     NaN    104    Mild  Bangalore        NaN
96     51.0     NaN    101  Strong    Kolkata        NaN
97     20.0     NaN    101    Mild  Bangalore        NaN
98      5.0     NaN     98  Strong     Mumbai        NaN
99     10.0     NaN     98  Strong    Kolkata        NaN

[100 rows x 6 columns]

In [35]:
df['newcity']=df["city"].where(df["city"]=="delhi",other=0)
print(df.head(10))

    age  gender  fever   cough       city  has_covid newcity
0  60.0     NaN    103    Mild     jaipur        NaN       0
1  27.0     NaN     50    Mild      Delhi        NaN       0
2  42.0     NaN     50    Mild      Delhi        NaN       0
3  31.0     NaN     98    Mild    Kolkata        NaN       0
4  65.0     NaN    101    Mild     Mumbai        NaN       0
5  84.0     NaN      0    Mild  Bangalore        NaN       0
6  14.0     NaN    101  Strong  Bangalore        NaN       0
7  20.0     NaN      0  Strong     Mumbai        NaN       0
8  19.0     NaN    100  Strong  Bangalore        NaN       0
9  64.0     NaN    101    Mild      Delhi        NaN       0

In [36]:
df['has_covid'] = df['has_covid'].map({"No": 0, "Yes": 1})

print(df['has_covid'])

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
95   NaN
96   NaN
97   NaN
98   NaN
99   NaN
Name: has_covid, Length: 100, dtype: float64

In [37]:
df['cough'] = df['cough'].map({"Mild": 0, "Strong": 1})

print(df['cough'])

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    1
97    0
98    1
99    1
Name: cough, Length: 100, dtype: int64

In [38]:
print(df.head(10))

    age  gender  fever  cough       city  has_covid newcity
0  60.0     NaN    103      0     jaipur        NaN       0
1  27.0     NaN     50      0      Delhi        NaN       0
2  42.0     NaN     50      0      Delhi        NaN       0
3  31.0     NaN     98      0    Kolkata        NaN       0
4  65.0     NaN    101      0     Mumbai        NaN       0
5  84.0     NaN      0      0  Bangalore        NaN       0
6  14.0     NaN    101      1  Bangalore        NaN       0
7  20.0     NaN      0      1     Mumbai        NaN       0
8  19.0     NaN    100      1  Bangalore        NaN       0
9  64.0     NaN    101      0      Delhi        NaN       0